# Generated by Django 3.2 on 2023-08-16 08:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_alter_user_sso_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='conversation_detail_modified_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
