# Generated by Django 3.2 on 2023-08-10 11:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_alter_user_sso_uid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('like', models.BooleanField(default=False)),
                ('feedback', models.TextField(null=True)),
                ('conversation_detail', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='chatbot.conversationdetail')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
