# Generated by Django 3.2 on 2023-08-18 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0005_conversation_conversation_detail_modified_at'),
        ('chatbot', '0005_feedback'),
    ]

    operations = [
    ]
