# Generated by Django 3.2 on 2023-09-14 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0009_alter_files_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='files',
            old_name='archive',
            new_name='is_deleted',
        ),
    ]
