# Generated by Django 3.2 on 2023-09-14 13:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0010_rename_archive_files_is_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch_id', models.UUIDField()),
                ('batch_processed', models.BooleanField(default=False)),
                ('abort', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='chatbot.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='filetrainingstatus',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='chatbot.filebatch'),
        ),
        migrations.DeleteModel(
            name='FileBatchStatus',
        ),
    ]
