# Generated by Django 3.2 on 2023-09-18 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0011_auto_20230914_1301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filetrainingstatus',
            name='file_name',
        ),
        migrations.AddField(
            model_name='filetrainingstatus',
            name='file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='chatbot.files'),
        ),
    ]
