# Generated by Django 3.2 on 2023-09-25 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0013_logs'),
    ]

    operations = [
        migrations.AddField(
            model_name='logs',
            name='file_url',
            field=models.URLField(null=True),
        ),
    ]
