# Generated by Django 3.2 on 2023-09-25 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0015_alter_logs_file_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='name',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='logs',
            name='file_url',
            field=models.TextField(null=True),
        ),
    ]
