# Generated by Django 3.2 on 2023-11-09 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0016_auto_20230925_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='whatsapp_chat',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='whatsapp_mobile_num',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
