# Generated by Django 3.2 on 2023-11-15 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0017_auto_20231109_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobile_number',
            field=models.CharField(max_length=30, null=True, unique=True),
        ),
    ]
