# Generated by Django 3.2 on 2023-11-15 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0018_alter_user_mobile_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='whatsapp_chat',
        ),
        migrations.RemoveField(
            model_name='user',
            name='whatsapp_mobile_num',
        ),
        migrations.AddField(
            model_name='conversation',
            name='whatsapp_chat',
            field=models.BooleanField(default=False),
        ),
    ]
