# Generated by Django 3.2 on 2023-12-14 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0019_auto_20231115_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='client',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='client_user_id',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
