# Generated by Django 3.2 on 2023-12-21 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0020_auto_20231214_1121'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='client_user_id',
            new_name='client_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='client',
        ),
        migrations.AlterField(
            model_name='user',
            name='sso_uid',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
