# Generated by Django 3.2 on 2024-01-24 07:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0021_auto_20231221_1338'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserWhatsappInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('profession', models.CharField(blank=True, max_length=50, null=True)),
                ('land_size', models.CharField(blank=True, max_length=50, null=True)),
                ('crop_growing', models.CharField(blank=True, max_length=50, null=True)),
                ('soil_type', models.CharField(blank=True, max_length=50, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='chatbot.user')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
