# Generated by Django 3.2 on 2024-02-16 11:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0022_userwhatsappinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsappFlow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('flow_id', models.CharField(max_length=255, unique=True)),
                ('flow_name', models.CharField(max_length=50, unique=True)),
                ('cta', models.CharField(max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
