# Generated by Django 3.2 on 2024-02-16 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0023_whatsappflow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userwhatsappinfo',
            name='crop_growing',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='userwhatsappinfo',
            name='land_size',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='userwhatsappinfo',
            name='name',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='userwhatsappinfo',
            name='profession',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='userwhatsappinfo',
            name='soil_type',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
