# Generated by Django 3.2 on 2024-05-02 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0024_auto_20240216_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='userwhatsappinfo',
            name='unsubscribe',
            field=models.BooleanField(default=False),
        ),
    ]
