# Generated by Django 3.2 on 2024-05-09 11:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0025_userwhatsappinfo_unsubscribe'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsappCronContent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('link', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(max_length=800)),
                ('content_type', models.CharField(max_length=50)),
                ('is_sent', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
